<a href="https://colab.research.google.com/github/Moukthika-y/Foundations-of-Data-Science-Lab/blob/main/Exp_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the libraries used throughout
import pandas as pd
import numpy as np

# Load the Titanic dataset (upload the csv to /content first)
titanic = pd.read_csv("/content/Titanic-Dataset (1).csv")
titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
# First WRITE titanic into different text formats (the PDF's files don't exist for titanic)

# Use columns without spaces/commas inside values so the separators work cleanly
# (Name and Cabin contain spaces and commas)
small = titanic[["PassengerId", "Survived", "Pclass", "Sex", "Age", "Fare", "Embarked"]]

# comma separated
small.to_csv("data_standard.csv", index=False)

# single-space separated
small.to_csv("data_spaces.txt", sep=" ", index=False)

# tab separated
small.to_csv("/content/data_tab_separated.tsv", sep="\t", index=False)

# variable amount of whitespace (to_string pads columns with different spaces)
with open("/content/data_variable_whitespace.txt", "w") as f:
    f.write(small.to_string(index=False))

In [3]:
# to read a text file with comma-separated data
df1 = pd.read_csv("data_standard.csv")

# text file with spaces
df2 = pd.read_csv("data_spaces.txt", sep=" ")

# text file with tab separated data
df3 = pd.read_csv("/content/data_tab_separated.tsv", sep='\t')

# text file with variable amounts of whitespace (regex: one or more spaces)
df4 = pd.read_csv("/content/data_variable_whitespace.txt", sep=r"\s+")

# show the first 5 rows of each
print(df1.head(), "\n")
print(df2.head(), "\n")
print(df3.head(), "\n")
print(df4.head())

   PassengerId  Survived  Pclass     Sex   Age     Fare Embarked
0            1         0       3    male  22.0   7.2500        S
1            2         1       1  female  38.0  71.2833        C
2            3         1       3  female  26.0   7.9250        S
3            4         1       1  female  35.0  53.1000        S
4            5         0       3    male  35.0   8.0500        S

   PassengerId  Survived  Pclass     Sex   Age     Fare Embarked
0            1         0       3    male  22.0   7.2500        S
1            2         1       1  female  38.0  71.2833        C
2            3         1       3  female  26.0   7.9250        S
3            4         1       1  female  35.0  53.1000        S
4            5         0       3    male  35.0   8.0500        S

   PassengerId  Survived  Pclass     Sex   Age     Fare Embarked
0            1         0       3    male  22.0   7.2500        S
1            2         1       1  female  38.0  71.2833        C
2            3         1       3  female  26.0   7.9250        S
3            4         1       1  female  35.0  53.1000        S
4            5         0       3    male  35.0   8.0500        S

   PassengerId  Survived  Pclass     Sex   Age     Fare Embarked
0            1         0       3    male  22.0   7.2500        S
1            2         1       1  female  38.0  71.2833        C
2            3         1       3  female  26.0   7.9250        S
3            4         1       1  female  35.0  53.1000        S
4            5         0       3    male  35.0   8.0500        S

In [4]:
# write titanic to an Excel file first
titanic.to_excel("/content/titanic_excel.xlsx", index=False)

# To read an excel file
ex = pd.read_excel("/content/titanic_excel.xlsx")
ex.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# reading data from an SQLite database
import sqlite3

# 1. Connect to a local SQLite database file (it is created if it doesn't exist)
conn = sqlite3.connect('titanic.db')

# write the titanic dataframe as a table named "passengers" (replace if it exists)
titanic.to_sql("passengers", conn, if_exists="replace", index=False)

# 2. Read the table back using a SQL query
query = "SELECT * FROM passengers;"
std = pd.read_sql_query(query, conn)
std.head()

# conn.close()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,None,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,None,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,None,S

In [6]:
# write titanic to an HTML file (first 10 rows keep it small)
titanic.head(10).to_html("/content/titanic_table.html", index=False)

page = pd.read_html("/content/titanic_table.html")
# read_html() returns a list of DataFrames,
# because an HTML page can contain multiple tables... use [0]
page[0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

# Preprocessing - Dropping and filling

In [8]:
df = titanic.copy()

print(df.head())

print("1st 5 rows\n")
print(df.head())       # first five rows
print("\nlast 5 rows")
print(df.tail())       # last five rows
print("Shape")
print(df.shape)        # (rows, columns)
print("Info")
df.info()              # column types and non-null counts

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
1st 5 rows

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

last 5 rows
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q
Shape
(891, 12)
Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
# Handling null/missing values
print("Missing vals\n")
print(df.isnull().sum())   # count of missing values per column
df.head()

print("Original shape:", df.shape)

df.dropna(axis=0)   # axis=0: rows
# delete rows with null values (only complete rows remain)

df.dropna(axis=1)
# delete columns with null values (Age, Cabin, Embarked are removed)

Missing vals

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
Original shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

In [10]:
print(df.dropna(how="all", axis=0).shape)   # drop a row only if ALL its values are null
print()
print(df.dropna(how="any", axis=0).shape)   # drop a row if it contains ANY 1 null value

print(df.dropna(how="all", axis=1).shape)   # drop a column only if ALL its values are null
print()
print(df.dropna(how="any", axis=1).shape)   # drop a column if it contains ANY 1 null value

(891, 12)

(183, 12)
(891, 12)

(891, 9)

In [11]:
df.dropna(thresh=11).shape
# Count-based: a row needs at least 11 non-null values (out of 12 columns) to be kept
# Rows with fewer valid values than thresh get dropped

# Filling missing values
print("Missing values: ")
print(df.isnull().sum())

df_copy = df.copy()   # work on a copy so the original is unchanged

# Embarked (text): fill with the mode (most frequent value)
df_copy["Embarked"] = df_copy["Embarked"].fillna(df_copy["Embarked"].mode()[0])

# Age: fill with the mean
df_copy["Age"] = df_copy["Age"].fillna(df_copy["Age"].mean())

# Age median version (saved in a separate column to compare with the mean)
df_copy["Age_median"] = df["Age"].fillna(df["Age"].median())

# Cabin: too many missing, so fill with a constant label
df_copy["Cabin"] = df_copy["Cabin"].fillna("Unknown")

print(df_copy.isnull().sum())
df_copy.head()

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64
PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
Age_median     0
dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_median
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Unknown,S,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Unknown,S,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Unknown,S,35.0

In [12]:
import random

# 1. Get a clean list of all valid Age values
valid_ages = df["Age"].dropna().tolist()

# 2. Replace missing values with a random choice, otherwise keep the value
df["Age"] = [
    random.choice(valid_ages) if pd.isna(x) else x for x in df["Age"]
]
df["Age"].isnull().sum()   # should now be 0

np.int64(0)

In [13]:
# Build a small messy dataset from titanic (first 12 passengers)
data = titanic[["PassengerId", "Name", "Sex", "Age", "Fare", "Embarked"]].head(12).copy()

# inconsistent text in Sex (upper case, mixed case, extra spaces)
data.loc[0, "Sex"] = "MALE"
data.loc[1, "Sex"] = "Female"
data.loc[3, "Sex"] = "   female  "
data.loc[6, "Sex"] = "MALE"

# inconsistent text in Embarked
data.loc[2, "Embarked"] = "s"
data.loc[7, "Embarked"] = "  S  "

# extra missing values (Age already has a real NaN at row 5)
data.loc[9, "Embarked"] = np.nan
data.loc[4, "Fare"] = np.nan

# invalid values (negative / impossible)
data.loc[3, "Age"] = -35.0
data.loc[8, "Age"] = 350.0
data.loc[10, "Fare"] = -20.0

# add 2 exact duplicate rows at the end
data = pd.concat([data, data.iloc[[1, 5]]], ignore_index=True)

data = pd.DataFrame(data)
data.shape
data.head()

,PassengerId,Name,Sex,Age,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",MALE,22.0,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,71.2833,C
2,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,s
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,-35.0,53.1000,S
4,5,"Allen, Mr. William Henry",male,35.0,NaN,S

In [14]:
# 1. Check duplicate values (returns True for every duplicate row)
duplicate_mask = data.duplicated()
print(duplicate_mask)

# 2. Find their sum
total_duplicates = duplicate_mask.sum()
print(f"Total duplicate rows: {total_duplicates}")

# 3. Drop them (keeping the first occurrence)
df_cleaned = data.drop_duplicates()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13     True
dtype: bool
Total duplicate rows: 2

In [15]:
# Drop duplicates based ONLY on the "Name" column
df_subset_name = data.drop_duplicates(subset=["Name"])

# Drop duplicates based on a combination of "Name" and "Sex"
df_subset_both = data.drop_duplicates(subset=["Name", "Sex"])
df_subset_both

,PassengerId,Name,Sex,Age,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",MALE,22.0,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",Female,38.0,71.2833,C
2,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,s
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,-35.0,53.1000,S
4,5,"Allen, Mr. William Henry",male,35.0,NaN,S
5,6,"Moran, Mr. James",male,NaN,8.4583,Q
6,7,"McCarthy, Mr. Timothy J",MALE,54.0,51.8625,S
7,8,"Palsson, Master. Gosta Leonard",male,2.0,21.0750,S
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,350.0,11.1333,S
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,30.0708,NaN
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,-20.0000,S
11,12,"Bonnell, Miss. Elizabeth",female,58.0,26.5500,S

In [16]:
# Sex should be in either upper or lower case
print("Upper case: ")
print(data["Sex"].str.upper())    # missing values stay NaN
print()
print("Lower case: ")
print(data["Sex"].str.lower())

Upper case:
0            MALE
1          FEMALE
2          FEMALE
3        FEMALE
4            MALE
5            MALE
6            MALE
7            MALE
8          FEMALE
9          FEMALE
10         FEMALE
11         FEMALE
12         FEMALE
13           MALE
Name: Sex, dtype: object

Lower case:
0            male
1          female
2          female
3        female
4            male
5            male
6            male
7            male
8          female
9          female
10         female
11         female
12         female
13           male
Name: Sex, dtype: object

In [17]:
# small demo of str.strip()
dff = pd.DataFrame({"Column": ["  Hello   world  ", "PYTHON      programming"]})
dff["Column"] = dff["Column"].str.strip()   # removes spaces at start and end only
print(dff)

                    Column
0            Hello   world
1  PYTHON      programming

In [18]:
# apply the same fixes to our messy data:
# strip spaces, then make the case consistent
data["Sex"] = data["Sex"].str.strip().str.lower()        # male / female
data["Embarked"] = data["Embarked"].str.strip().str.upper()   # S / C / Q
print(data["Sex"].unique())
print(data["Embarked"].unique())

['male' 'female']
['S' 'C' 'Q' nan]

In [19]:
# rename() takes {old name: new name}
data = data.rename(columns={"PassengerId": "Passenger_Id", "Sex": "Gender"})
data

,Passenger_Id,Name,Gender,Age,Fare,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,C
2,3,"Heikkinen, Miss. Laina",female,26.0,7.9250,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,-35.0,53.1000,S
4,5,"Allen, Mr. William Henry",male,35.0,NaN,S
5,6,"Moran, Mr. James",male,NaN,8.4583,Q
6,7,"McCarthy, Mr. Timothy J",male,54.0,51.8625,S
7,8,"Palsson, Master. Gosta Leonard",male,2.0,21.0750,S
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,350.0,11.1333,S
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,30.0708,NaN
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,-20.0000,S
11,12,"Bonnell, Miss. Elizabeth",female,58.0,26.5500,S
12,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,C
13,6,"Moran, Mr. James",male,NaN,8.4583,Q

In [20]:
# Valid Age should be between 0 and 100, and Fare cannot be negative

# 1. Create a boolean mask for rows outside the valid range
invalid_mask = (data["Age"] < 0) | (data["Age"] > 100) | (data["Fare"] < 0)

# 2. Extract and view the problematic rows
inconsistent_data = data[invalid_mask]
print(f"Found {len(inconsistent_data)} problematic rows:")
print(inconsistent_data[["Age", "Fare"]])

# Replace out-of-range values with NaN
data.loc[(data["Age"] < 0) | (data["Age"] > 100), "Age"] = np.nan
data.loc[data["Fare"] < 0, "Fare"] = np.nan
data[["Age", "Fare"]]

Found 3 problematic rows:
      Age     Fare
3   -35.0  53.1000
8   350.0  11.1333
10    4.0 -20.0000

     Age     Fare
0   22.0   7.2500
1   38.0  71.2833
2   26.0   7.9250
3    NaN  53.1000
4   35.0      NaN
5    NaN   8.4583
6   54.0  51.8625
7    2.0  21.0750
8    NaN  11.1333
9   14.0  30.0708
10   4.0      NaN
11  58.0  26.5500
12  38.0  71.2833
13   NaN   8.4583

In [21]:
# 1. Identify Outliers using IQR (on the real Fare column)
df = titanic.copy()

Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)
print(df["Fare"].describe())
IQR = Q3 - Q1

# Define IQR boundaries
lower_iqr = Q1 - 1.5 * IQR
upper_iqr = Q3 + 1.5 * IQR

# Create a mask for rows that IQR flags as outliers
outlier_mask = (df["Fare"] < lower_iqr) | (df["Fare"] > upper_iqr)
print("Number of outliers:", outlier_mask.sum())

count    891.000000
mean      32.204208
std       49.693429
min        0.000000
25%        7.910400
50%       14.454200
75%       31.000000
max      512.329200
Name: Fare, dtype: float64
Number of outliers: 116

In [22]:
# 2. Calculate Z-score boundaries based ONLY on the clean, valid data
clean_data = df.loc[~outlier_mask, "Fare"]
mean = clean_data.mean()
std = clean_data.std()

# Define Z-score limits (3 standard deviations)
lower_z_limit = mean - (3 * std)
upper_z_limit = mean + (3 * std)
print(lower_z_limit, upper_z_limit)

-22.912165351685836 58.55634677104067

In [23]:
# 3. Impute: cap the IQR-flagged outliers at the Z-score boundaries
df["Fare"] = np.where(
    df["Fare"] > upper_iqr,
    upper_z_limit,
    np.where(df["Fare"] < lower_iqr, lower_z_limit, df["Fare"]),
)
print("Max Fare before:", titanic["Fare"].max())
print("Max Fare after :", df["Fare"].max())
df["Fare"]

Max Fare before: 512.3292
Max Fare after : 65.0

0       7.250000
1      58.556347
2       7.925000
3      53.100000
4       8.050000
         ...
886    13.000000
887    30.000000
888    23.450000
889    30.000000
890     7.750000
Name: Fare, Length: 891, dtype: float64

# Standardisation and Normalisation

In [25]:
import time


# Age has missing values, so fill them first (median) to avoid NaN in the results
df["Age"] = df["Age"].fillna(df["Age"].median())
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250000,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,58.556347,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925000,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.100000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050000,NaN,S

In [26]:
# columns to be processed
features = ["Age", "Fare", "SibSp", "Parch"]

# --- PROCESS 1: STANDARDISATION TIMER ---
start_std = time.perf_counter()
for col in features:
    mean_val = df[col].mean()
    std_val = df[col].std()
    # z-score: mean becomes 0 and std becomes 1
    df[f"{col}_standardised"] = (df[col] - mean_val) / std_val
end_std = time.perf_counter()
std_time_ms = (end_std - start_std) * 1000   # seconds -> milliseconds

In [27]:
# --- PROCESS 2: NORMALISATION TIMER ---
start_norm = time.perf_counter()
for col in features:
    min_val = df[col].min()
    max_val = df[col].max()
    # Min-Max normalisation: scales values between 0 and 1
    df[f"{col}_normalised"] = (df[col] - min_val) / (max_val - min_val)
end_norm = time.perf_counter()
norm_time_ms = (end_norm - start_norm) * 1000

In [28]:
# Print benchmark results
print(f"Standardisation Time : {std_time_ms:.4f} ms")
print(f"Normalisation Time   : {norm_time_ms:.4f} ms")
print(f"Total Pipeline Time  : {std_time_ms + norm_time_ms:.4f} ms")

df.head()

Standardisation Time : 4.6661 ms
Normalisation Time   : 6.1710 ms
Total Pipeline Time  : 10.8371 ms

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_standardised,Fare_standardised,SibSp_standardised,Parch_standardised,Age_normalised,Fare_normalised,SibSp_normalised,Parch_normalised
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.250000,NaN,S,-0.565419,-0.850463,0.432550,-0.473408,0.271174,0.111538,0.125,0.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,58.556347,C85,C,0.663488,1.898090,0.432550,-0.473408,0.472229,0.900867,0.125,0.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925000,NaN,S,-0.258192,-0.814302,-0.474279,-0.473408,0.321438,0.121923,0.000,0.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.100000,C123,S,0.433068,1.605786,0.432550,-0.473408,0.434531,0.816923,0.125,0.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.050000,NaN,S,0.433068,-0.807606,-0.474279,-0.473408,0.434531,0.123846,0.000,0.0

# Merging

In [29]:
# df1: first 5 passengers (PassengerId 1-5) with personal details
df1 = titanic[["PassengerId", "Name", "Sex", "Age"]].iloc[0:5].copy()

# df2: PassengerId 3-7 with ticket details (only Ids 3, 4, 5 overlap with df1)
df2 = titanic[["PassengerId", "Pclass", "Fare", "Embarked"]].iloc[2:7].copy()

print("--- Original DataFrames ---")
print("Passenger DataFrame:\n", df1)
print("Ticket DataFrame:\n", df2)

--- Original DataFrames ---
Passenger DataFrame:
    PassengerId                                               Name     Sex  \
0            1                            Braund, Mr. Owen Harris    male
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2            3                             Heikkinen, Miss. Laina  female
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4            5                           Allen, Mr. William Henry    male

    Age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0
Ticket DataFrame:
    PassengerId  Pclass     Fare Embarked
2            3       3   7.9250        S
3            4       1  53.1000        S
4            5       3   8.0500        S
5            6       3   8.4583        Q
6            7       1  51.8625        S

In [30]:
# INNER MERGE: Keeps only rows where PassengerId exists in BOTH DataFrames.
inner_merge = pd.merge(df1, df2, on='PassengerId', how='inner')
print("--- Inner Merge ---")
print(inner_merge, "\n")

# OUTER MERGE: Keeps ALL rows from both DataFrames, filling missing values with NaN.
outer_merge = pd.merge(df1, df2, on='PassengerId', how='outer')
print("--- Outer Merge ---")
print(outer_merge, "\n")

# LEFT MERGE: Keeps all rows from the left (passenger) DataFrame, matching right where possible.
left_merge = pd.merge(df1, df2, on='PassengerId', how='left')
print("--- Left Merge ---")
print(left_merge, "\n")

# RIGHT MERGE: Keeps all rows from the right (ticket) DataFrame, matching left where possible.
right_merge = pd.merge(df1, df2, on='PassengerId', how='right')
print("--- Right Merge ---")
print(right_merge)

--- Inner Merge ---
   PassengerId                                          Name     Sex   Age  \
0            3                        Heikkinen, Miss. Laina  female  26.0
1            4  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
2            5                      Allen, Mr. William Henry    male  35.0

   Pclass    Fare Embarked
0       3   7.925        S
1       1  53.100        S
2       3   8.050        S

--- Outer Merge ---
   PassengerId                                               Name     Sex  \
0            1                            Braund, Mr. Owen Harris    male
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2            3                             Heikkinen, Miss. Laina  female
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4            5                           Allen, Mr. William Henry    male
5            6                                                NaN     NaN
6            7                                                NaN     NaN

    Age  Pclass     Fare Embarked
0  22.0     NaN      NaN      NaN
1  38.0     NaN      NaN      NaN
2  26.0     3.0   7.9250        S
3  35.0     1.0  53.1000        S
4  35.0     3.0   8.0500        S
5   NaN     3.0   8.4583        Q
6   NaN     1.0  51.8625        S

--- Left Merge ---
   PassengerId                                               Name     Sex  \
0            1                            Braund, Mr. Owen Harris    male
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2            3                             Heikkinen, Miss. Laina  female
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4            5                           Allen, Mr. William Henry    male

    Age  Pclass    Fare Embarked
0  22.0     NaN     NaN      NaN
1  38.0     NaN     NaN      NaN
2  26.0     3.0   7.925        S
3  35.0     1.0  53.100        S
4  35.0     3.0   8.050        S

--- Right Merge ---
   PassengerId                                          Name     Sex   Age  \
0            3                        Heikkinen, Miss. Laina  female  26.0
1            4  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
2            5                      Allen, Mr. William Henry    male  35.0
3            6                                           NaN     NaN   NaN
4            7                                           NaN     NaN   NaN

   Pclass     Fare Embarked
0       3   7.9250        S
1       1  53.1000        S
2       3   8.0500        S
3       3   8.4583        Q
4       1  51.8625        S

# Concatenation

In [33]:
# df4: same columns as df1 but different passengers (PassengerId 11-15)
df4 = titanic[["PassengerId", "Name", "Sex", "Age"]].iloc[10:15].reset_index(drop=True)

# concatenate vertically

# 1. Stack vertically and reset the index
df_stacked = pd.concat([df1, df4], axis=0, ignore_index=True)
df_stacked

# concatenate horizontally (side by side, rows matched by index)
df_horizontal = pd.concat([df1, df4], axis=1)
df_horizontal

# stack frames with different columns: missing columns are filled with NaN,
# and the old index numbers are kept (so they repeat)
df_total = pd.concat([df4, inner_merge])
df_total

,PassengerId,Name,Sex,Age,Pclass,Fare,Embarked
0,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,NaN,NaN,NaN
1,12,"Bonnell, Miss. Elizabeth",female,58.0,NaN,NaN,NaN
2,13,"Saundercock, Mr. William Henry",male,20.0,NaN,NaN,NaN
3,14,"Andersson, Mr. Anders Johan",male,39.0,NaN,NaN,NaN
4,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,NaN,NaN,NaN
0,3,"Heikkinen, Miss. Laina",female,26.0,3.0,7.925,S
1,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,53.100,S
2,5,"Allen, Mr. William Henry",male,35.0,3.0,8.050,S

# Filtering

In [34]:
# Filtering with one condition: names of male passengers in outer_merge
outer_merge[(outer_merge["Sex"] == "male")].Name

# OR condition: Sex is female OR Fare is above 50
# | means OR, & means AND; each condition goes in brackets
outer_merge[(outer_merge["Sex"] == "female") | (outer_merge["Fare"] > 50)]

# AND condition (extra): Sex is female AND Fare is above 10
outer_merge[(outer_merge["Sex"] == "female") & (outer_merge["Fare"] > 10)]

,PassengerId,Name,Sex,Age,Pclass,Fare,Embarked
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,53.1,S